#!/bin/bash

#exphead='tFja'
exphead='tFks'

for id in {a..b} ; do

exp=${exphead}${id}

mkdir -p ${exp}_output

# every 50 years:
#scp ggdjl@bc4login.acrc.bristol.ac.uk:/user/home/ggdjl/dump2hold/${exp}/datam/*#pi*[0,5]0dc+ ./${exp}_output/

# every 5 years:
scp ggdjl@bc4login.acrc.bristol.ac.uk:/user/home/ggdjl/dump2hold/${exp}/datam/*#pi*[0,5]dc+ ./${exp}_output/

done








exit
