#!/bin/ksh

exp='texz'
year='000005850'
tail='1'

thisdir='extract_tmp'
mkdir -p ${thisdir}

newdir=/home/bridge/ggdjl/ClimateOutput/scotese_restarts/${exp}${tail}
mkdir -p ${newdir}

exp1a=${exp}
exp1b=`sed 's/./\U&/4' <<< "${exp1a}"`
exp1c=`sed 's/./\U&/3' <<< "${exp1a}"`
exp1d=`sed 's/./\U&/3' <<< "${exp1b}"`
exp1e=`sed 's/./\U&/2' <<< "${exp1a}"`

expids="${exp1a} ${exp1b} ${exp1c} ${exp1d} ${exp1e}"

for expid in ${expids} ; do

my_loop={a..z}
if [ "$expid" = ${exp1e} ] ; then
  my_loop={a..e}
fi
#my_loop={a..b}

for id in ${my_loop} ; do
expl=${expid}${id}${tail}
exp=${expid}${id}


tar xvf /home/bridge/swsvalde/ummodel/data/${expl}/expt_archive/${expl}.taz -C ./${thisdir}/
\cp ${thisdir}/${exp}/datam/${expid}${id}?#da${year}c1+ ${newdir}/
\rm -r ${thisdir}/${exp}

done

done










exit
