#!/bin/bash
#

add_ftp=0 # [only works if file has some text in already]
mk_dirs=1

###  get args
if [ "$#" -ne 2 ]; then
    echo "Illegal number of options: must be equal to 2"
    exit
fi
#

if [ $USER != 'ggdjl' ] ; then
  echo "needs to run as ggdjl"
  exit
fi

explist=$1
mymachine=$2

for exp in ${explist} ; do

expid=`echo ${exp} | head -c 4`
let=`echo ${exp:4:1}`

echo ${exp}
echo ${mymachine}

if [ ${mymachine} != 'triassic' ] && [ ${mymachine} != 'silurian' ] ; then
echo 'machine not valid...stop'
exit
fi

# make directories
if [ ${mk_dirs} -eq 1 ] ; then

dir1=/export/${mymachine}/array-01/ggdjl/${exp} 
if [ ! -d ${dir1} ]; then
mkdir -p ${dir1}
chmod a+rwx ${dir1}
fi

dir2=/home/bridge/swsvalde/umdata/${exp}
if [ ! -d ${dir2} ]; then
ln -s ${dir1} ${dir2}
chmod a+rwx ${dir2}
fi

fi


# add to ftp_control [only works if file has some text in already]
if [ ${add_ftp} -eq 1 ] ; then
file=/home/bridge/ggdjl/bin/ftp_sh.bc4.params

if ! grep -q ${exp} ${file} ; then
    echo 'need to add to ftp list'
    sed -i " 1 s/.*/& ${exp}/" ${file}
fi
fi

done


