#!/bin/bash
#

add_ftp=1
mk_dirs=0

###  get args
if [ "$#" -eq 0 ]; then
    echo "Illegal number of options: must be greater than 0"
    exit
fi
#

if [ $USER != 'ggdjl' ] ; then
  echo "needs to run as ggdjl"
  exit
fi

explist=$*

for exp in ${explist} ; do

expid=`echo ${exp} | head -c 4`
let=`echo ${exp:4:1}`

echo ${exp}


# make directories
if [ ${mk_dirs} -ne 0 ] ; then
dir1=/export/silurian/array-01/ggdjl/${exp} 
if [ ! -d ${dir1} ]; then
mkdir -p ${dir1}
chmod a+rwx ${dir1}
fi

dir2=/home/bridge/swsvalde/umdata/${exp}
if [ ! -d ${dir2} ]; then
ln -s ${dir1} ${dir2}
chmod a+rwx ${dir2}
fi

fi


# add to ftp_control
if [ ${add_ftp} -ne 0 ] ; then
file=/home/bridge/ggdjl/bin/ftp_sh.bc4.params

if ! grep -q ${exp} ${file} ; then
    echo 'need to add'
    sed -i " 1 s/.*/& ${exp}/" ${file}
fi
fi

done


