#!/bin/bash

#restartdate='#da000003850c1+' # teyd
restartdate='#da000007850c1+' # teye

#target_dir='teyd_newislands' # teyd
target_dir='teye_newislands' # teye

# 0 = get files
# 1 = test and plot
# 2 = submit and plot and crop
# 3 = only ridge
# 4 = only stat

mytype=3

# options for make_new
raw='0'
stat='1'
inte='0'

if [ ${mytype} -eq 4 ] ; then
get_files='0'
new_islands='0'
run_xancil='1'
make_derived='1'
ridge='0'
send_files_bc='1'
send_atmos_bc='1'
send_files_puma='0'
plot_islands='0'
crop_islands='0'
fi

if [ ${mytype} -eq 3 ] ; then
get_files='0'
new_islands='0'
run_xancil='1'
make_derived='1'
ridge='1'
send_files_bc='1'
send_atmos_bc='1'
send_files_puma='0'
plot_islands='0'
crop_islands='0'
fi

if [ ${mytype} -eq 2 ] ; then
get_files='0'
new_islands='1'
run_xancil='1'
make_derived='1'
stat='1'
ridge='0'
send_files_bc='1'
send_atmos_bc='1'
send_files_puma='1'
plot_islands='1'
crop_islands='1'
fi

if [ ${mytype} -eq 1 ] ; then
get_files='0'
new_islands='1'
run_xancil='1'
make_derived='0'
send_files_bc='0'
send_files_puma='0'
plot_islands='1'
crop_islands='0'
fi

if [ ${mytype} -eq 0 ] ; then
get_files='1'
new_islands='0'
run_xancil='0'
make_derived='0'
send_files_bc='0'
send_files_puma='0'
plot_islands='0'
crop_islands='0'
fi


###  get args
if [ "$#" -ne 1 ]; then
    echo "Illegal number of options: must be 1"
    exit
fi

###  setup
exp=${1}
mkdir -p ${exp}
cd ${exp}


if [ ${get_files} -eq 1 ] ; then

###  get restart dump
archfile="/home/bridge/swsvalde/ummodel/data/${exp}/expt_archive/${exp}.taz"
if [ -f ${archfile} ]; then
  \cp ${archfile} .
  tar xvf ${archfile} ${exp}/datam/${exp}a"${restartdate}"
  tar xvf ${archfile} ${exp}/datam/${exp}o"${restartdate}"
  \cp ${exp}/datam/${exp}?"${restartdate}" .
  \rm -r ${exp}
  \rm -r ${exp}.taz
else
  echo "Error: ${archfile} not found.	."
  exit 1
fi

###  get ocean land-sea mask
cp /home/bridge/swsvalde/ummodel/data/${exp}/inidata/${exp}.qrparm.omask.nc .

fi

if [ ${new_islands} -eq 1 ] ; then

### get old islands
/home/bridge/ggdjl/ggdjl/um/scripts/bath_islands_scr_new ${exp}o${restartdate} bath_${exp}_oldislands.nc islands_${exp}_oldislands.nc ascii_${exp}_oldislands.isl umui_${exp}_oldislands.dat

printf "\n"
echo "**Now run isla [after module load isla/1.0.1] on ${exp}/${exp}.qrparm.omask.nc , consolidating/removing/adding islands as necessary"
read -rsp $'**Then press any key to continue...\n' -n1 key
echo "**Output ascii file to ${exp}/ascii_${exp}_newislands_isla.isl"
read -rsp $'**Then press any key to continue...\n' -n1 key
echo "**Edit ${exp}/ascii_${exp}_newislands_isla.nc to add one to 2nd and 4th elements [if not circular] and save to ${exp}/ascii_${exp}_newislands_corr.isl "
read -rsp $'**Then press any key to continue...\n' -n1 key
echo 'Done'

fi


if [ ${run_xancil} -eq 1 ] ; then

### create and run xancil job
suff='job'
jobfile="xancil.${exp}.${suff}"
\cp ../xancil.SKEL.${suff} ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/RESTARTDATE/${restartdate}/g" ${jobfile}
xancil -j ${jobfile} -x
\rm xancil.namelist

### get new islands
/home/bridge/ggdjl/ggdjl/um/scripts/bath_islands_scr_new ${exp}o${restartdate}_newislands bath_${exp}_newislands.nc islands_${exp}_newislands.nc ascii_${exp}_newislands_check.isl umui_${exp}_newislands.dat

fi

restartfile="${exp}o${restartdate}_newislands"
restartfile_atmos="${exp}a${restartdate}"

if [ ${make_derived} -eq 1 ] ; then

### create stationary restart file if required
if [ ${stat} -eq 1  ] ; then
um2nc ${restartfile}
cdo expr,'streamFn_uo=0.0;field612_uo=0.0;field613_uo=0.0;field614_uo=0.0;' ${restartfile}.nc ${restartfile}_mod1.nc 
# to preserve land-sea mask:
cdo -setrtoc,-1e99,1e99,0 -selvar,ucurrBaro_dpth,vcurrBaro_dpth ${restartfile}.nc ${restartfile}_mod2.nc
# zero everywhere:
#cdo expr,'ucurrBaro_dpth=0.0;vcurrBaro_dpth=0.0;' ${restartfile}.nc ${restartfile}_mod2.nc
suff='initcond.job'
jobfile="xancil.${exp}.${suff}"
\cp ../xancil.SKEL.${suff} ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/RESTARTDATE/${restartdate}/g" ${jobfile}
xancil -j ${jobfile} -x
\rm xancil.namelist
\rm ${restartfile}.nc ${restartfile}_mod1.nc ${restartfile}_mod2.nc

fi

### create interpolated restart file if required
if [ ${inte} -eq 1  ] ; then
um2nc ${restartfile}
cdo -fillmiss -fillmiss ${restartfile}.nc ${restartfile}_fillmiss.nc
suff='interp.job'
jobfile="xancil.${exp}.${suff}"
\cp ../xancil.SKEL.${suff} ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/RESTARTDATE/${restartdate}/g" ${jobfile}
xancil -j ${jobfile} -x
\rm xancil.namelist
\rm ${restartfile}.nc ${restartfile}_fillmiss.nc

fi

### create ridge restart file if required
if [ ${ridge} -eq 1  ] ; then
suff='ridge.job'
jobfile="xancil.${exp}.${suff}"
\cp ../xancil.SKEL.${suff} ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/RESTARTDATE/${restartdate}/g" ${jobfile}
xancil -j ${jobfile} -x
\rm xancil.namelist
fi

fi


if [ ${send_files_bc} -eq 1 ] ; then

if [ ${raw} -eq 1  ] ; then newname='' ; fi
if [ ${stat} -eq 1  ] ; then newname='_stat' ; fi
if [ ${inte} -eq 1  ] ; then newname='_interp' ; fi
if [ ${ridge} -eq 1  ] ; then newname='_stat_ridge' ; fi


scp ${restartfile}${newname} ggdjl@bc4login.acrc.bris.ac.uk:/mnt/storage/home/ggdjl/dump2hold/dumps_deeptime_djl/${target_dir}
ssh ggdjl@bc4login.acrc.bris.ac.uk "ls; pwd; cd /mnt/storage/home/ggdjl/dump2hold/dumps_deeptime_djl/${target_dir} ; rm ${exp}.ocean ; ln -s ${restartfile}${newname} ${exp}.ocean" 

if [ ${send_atmos_bc} -eq 1 ] ; then
scp ${restartfile_atmos} ggdjl@bc4login.acrc.bris.ac.uk:/mnt/storage/home/ggdjl/dump2hold/dumps_deeptime_djl/${target_dir}
ssh ggdjl@bc4login.acrc.bris.ac.uk "ls; pwd; cd /mnt/storage/home/ggdjl/dump2hold/dumps_deeptime_djl/${target_dir} ; rm ${exp}.atmos ; ln -s ${restartfile_atmos} ${exp}.atmos" 
fi

fi


if [ ${send_files_puma} -eq 1 ] ; then

eval $(ssh-agent) ; ssh-add  ~/.ssh/id_rsa_puma ; scp umui_${exp}_newislands.dat ggdjl@puma.nerc.ac.uk:/home/ggdjl/scotese/islands
echo "****REMEMBER TO RUN make_12_jobs_scotese_03_djl on puma****"
fi

if [ ${plot_islands} -eq 1 ] ; then

jobfile="ncl.${exp}.islands.ncl"
\cp ../ncl.SKEL.islands.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
ncl ${jobfile}

if [ ${crop_islands} -eq 1 ] ; then
pdfcrop newislands_${exp}.pdf &
fi

fi

echo "****REMEMBER TO RUN make_12_jobs_scotese_03_djl on puma****"

exit
