#!/bin/ksh

indir_root=/home/bridge/swsvalde/ummodel

for exproot in tfgw tfgW tfGw tfGW tFgw ; do
#for exproot in tfGW ; do
#for exproot in tFgw ; do
   my_loop={a..z}
#   my_loop={a..e}
#   my_loop='a'

   if [ "$exproot" = "tFgw" ] ; then
      my_loop={a..e}
   fi

   for id in ${my_loop} ; do

     exp=${exproot}${id}
     echo ${exp}
     
     indir=${indir_root}/data/${exp}/climate
     crnum=36
     for type in pc pd pf pt ; do
     mynum=`ls ${indir}/${exp}??${type}*.nc 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != ${crnum} ] ; then
       echo 'DODGY '${type}' '${mynum}' '${crnum}
     fi
     done
     for type in pg ; do
     crnum=2
     mynum=`ls ${indir}/${exp}??${type}*.nc 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != ${crnum} ] ; then
       echo 'DODGY '${type}' '${mynum}' '${crnum}
     fi
     done

     dir=standard_new_plots
     indir=${indir_root}/data/${exp}/${dir}
     crnum=0
     mynum=`ls ${indir}/*.gif | wc | awk {'print $1}'`
     if [ ${mynum} == ${crnum} ] ; then
       echo 'DODGY '${dir}' '${mynum}' !='${crnum}
     fi

     dir=sed
     indir=${indir_root}/data/${exp}/${dir}
     crnum=3
     mynum=`ls ${indir}/* 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != ${crnum} ] ; then
       echo 'DODGY '${dir}' '${mynum}' '${crnum}
     fi

     dir=monthly 
     indir=${indir_root}/data/${exp}/${dir}
     crnum=73
     mynum=`ls ${indir}/* 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != 73 ] ; then
       echo 'DODGY '${dir}' '${mynum}' '${crnum}
     fi

     dir=merid_atm
     indir=${indir_root}/data/${exp}/${dir}
     crnum=18
     mynum=`ls ${indir}/* 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != ${crnum} ] ; then
       echo 'DODGY '${dir}' '${mynum}' '${crnum}
     fi

     dir=biome
     indir=${indir_root}/data/${exp}/${dir}
     crnum=6
     mynum=`ls ${indir}/* 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != ${crnum} ] ; then
       echo 'DODGY '${dir}' '${mynum}' '${crnum}
     fi

     dir=wetland
     indir=${indir_root}/data/${exp}/${dir}
     crnum=13
     mynum=`ls ${indir}/* 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != ${crnum} ] ; then
       echo 'DODGY '${dir}' '${mynum}' '${crnum}
     fi

     dir=storms
     indir=${indir_root}/data/${exp}/${dir}
     crnum=37
     mynum=`ls ${indir}/* 2> /dev/null | wc | awk {'print $1}'`
     if [ ${mynum} != ${crnum} ] ; then
       echo 'DODGY '${dir}' '${mynum}' '${crnum}
     fi

     dir=ggdjl_${exp}
     indir=${indir_root}/access/${dir}
     crnum=0
     for file in `ls ${indir}/*.err` ; do
       mynum=`ls -l ${file} | awk {'print $5}'`
       if [ ${mynum} != 0 ] ; then
       echo 'DODGY '${dir}' '${file}' '${mynum}' != '${crnum}
       fi
     done

   done
done

exit
