#!/bin/ksh

indir_root=/home/bridge/ggdjl/umdata

for exproot in tfgw tfgW tfGw tfGW tFgw ; do

   my_loop={a..z}

   if [ "$exproot" = "tFgw" ] ; then
      my_loop={a..e}
   fi

   for id in ${my_loop} ; do

     exp=${exproot}${id}
     indir=${indir_root}/${exp}
     echo ${exp}


     for type in pc pd pf pi ; do
     mynum=`ls ${indir}/${type}/${exp}??${type}*.nc | wc | awk {'print $1}'`
     if [ ${mynum} != 12601 ] ; then
       echo 'DODGY '${type}' '${mynum}' 12601'
     fi
     done

     for type in pg ; do
     mynum=`ls ${indir}/${type}/${exp}??${type}*.nc | wc | awk {'print $1}'`
     if [ ${mynum} != 1050 ] ; then
       echo 'DODGY '${type}' '${mynum}' 1050'
     fi
     done

     for type in pa pb ; do
     mynum=`ls ${indir}/${type}/${exp}??${type}*.nc | wc | awk {'print $1}'`
     if [ ${mynum} != 600 ] ; then
       echo 'DODGY '${type}' '${mynum}' 600'
     fi
     done

     for type in pt ; do
     mynum=`ls ${indir}/${type}/${exp}??${type}* | wc | awk {'print $1}'`
     if [ ${mynum} != 12600 ] ; then
       echo 'DODGY '${type}' '${mynum}' 12600'
     fi
     done


   done
done

exit
