#!/bin/ksh

#convert temp_scotese_time.eps -density 100 temp_scotese.png
#convert forcings_time.eps -density 100 forcings_time.png

#for ty in temp_scotese_time forcings_time solar_time co2_time clim_temp_pro_time clim_temp_new_time resid_temp_time ; do

#for ty in clim_temp_pro_time ; do

#for ty in clim_temp_new_time ; do

#for ty in resid_temp_time ; do

#for ty in polamp_temp_time polamp_sst_time ; do

#for ty in polampxtemp_temp_scatter polampxtemp_sst_scatter ; do

#for ty in forcings_time_1 co2_time_1 ; do

#for ty in polampxtemp_sst_scatter ; do

#for ty in ice_time ; do

#for ty in grads_time scattemp_time clim_temp_egu_time ; do

# for ty in climsens_time ; do

## FOR EGU:

#for ty in temp_scotese_time_03 ; do

#for ty in co2_time_0 solar_time ; do

#for ty in clim_temp_pro_time ; do

#for ty in clim_temp_new_time forcings_time_2 ; do

#for ty in resid_temp_time ; do

#for ty in grads_time ; do

#for ty in polamp_temp_time polamp_sst_time polampxtemp_temp_scatter polampxtemp_sst_scatter; do

#for ty in co2_time_2; do

#for ty in clim_temp_egu_time scattemp_time ; do

#for ty in climsens_time ; do

#for ty in ess_co2_temp_ ; do
#for n in 0 1 2 3 4 5 6 7 8 ; do
#gs -dSAFER -dEPSCrop -r600 -sDEVICE=pngalpha -o ${ty}${n}.png ${ty}${n}.eps
#done
#done

#for file in gmstcont_time polampcont_time gmstcont_time_percent polampcont_time_percent ; do

#for file in seasxtemp_cmmt_scatter seasxtemp_wmmt_scatter ; do

#for file in fluxes/tmp_lat_change_aprp_tFkee ; do

#for file in temp_scotese_time_04 ; do

#for file in co2_time_2 solar_time_0  ; do

#for file in clim_temp_geo_time ; do


#for file in ../Figure_polampsat ; do

#for file in mixed_time_tfke_mean2 ; do

#for file in grads_time_temp_tfke_abs grads_time_temp_tfke_anom ; do

#for file in grads_time_prec_tfke_abs grads_time_prec_tfke_anom ; do

#for file in grads_time_prec_texp_anom grads_time_prec_texx_anom ; do

#for file in grads_time_mixd_tfke_abs grads_time_mixd_tfke_anom grads_time_mixd_texp_anom grads_time_mixd_texx_anom ; do

#for file in scatt_frad-gmst_tfke scatt_gmst-prec_tfke ; do

#for file in grads_time_pme_texx_anom grads_time_evap_texx_anom ; do

for file in grads_time_cont_texx_anom grads_time_mprec_texx_anom ; do

gs -dSAFER -dEPSCrop -r600 -sDEVICE=pngalpha -o ${file}.png ${file}.eps
done



exit
