#!/bin/ksh

indir_root=/home/bridge/ggdjl/um_climates

explist=''

for exproot in tfgw tfgW tfGw tfGW tFgw ; do
   if [ "$exproot" = "tfgw" ] ; then
      exproot_old="teye"      
      my_loop={a..z}
   elif [ "$exproot" = "tfgW" ] ; then
      exproot_old="teyE"
      my_loop={a..z}
   elif [ "$exproot" = "tfGw" ] ; then
      exproot_old="teYe"
      my_loop={a..z}
   elif [ "$exproot" = "tfGW" ] ; then
      exproot_old="teYE"
      my_loop={a..z}
   elif [ "$exproot" = "tFgw" ] ; then
      exproot_old="tEye"
      my_loop={a..e}
   fi

   for id in ${my_loop} ; do

     exp=${exproot}${id}
     exr=${exproot_old}${id}

     explist_uv_00=${explist_uv_00}' plots/uv_'${exp}_00'.pdf'
     explist_uv_11=${explist_uv_11}' plots/uv_'${exp}_11'.pdf'
     explist_uv_15=${explist_uv_15}' plots/uv_'${exp}_15'.pdf'
     explist_stream=${explist_stream}' plots/streamfn_'${exp}'.pdf'
     explist_mixed=${explist_mixed}' plots/mixed_'${exp}'.pdf'
     explist_merid=${explist_merid}' plots/merid_'${exp}'.pdf'
     explist_wind=${explist_wind}' plots/wind_'${exp}'.pdf'
     explist_salin=${explist_salin}' plots/salin_'${exp}'.pdf'
     explist_temp=${explist_temp}' plots/temp_'${exp}'.pdf'
     explist_topo=${explist_topo}' plots/topo_'${exp}'.pdf'
     explist_islands=${explist_islands}' ../islands/'${exr}'/newislands_'${exr}'-crop.pdf'

   done
done

convert -loop 0 -delay 20 ${explist_uv_00} anim_uv_00.gif
convert -loop 0 -delay 20 ${explist_uv_11} anim_uv_11.gif
convert -loop 0 -delay 20 ${explist_uv_15} anim_uv_15.gif
convert -loop 0 -delay 20 ${explist_stream} anim_stream.gif
convert -loop 0 -delay 20 ${explist_mixed} anim_mixed.gif
convert -loop 0 -delay 20 ${explist_merid} anim_merid.gif
convert -loop 0 -delay 20 ${explist_wind} anim_wind.gif
convert -loop 0 -delay 20 ${explist_salin} anim_salin.gif
convert -loop 0 -delay 20 ${explist_temp} anim_temp.gif
#convert -loop 0 -delay 20 ${explist_topo} anim_topo.gif
#convert -loop 0 -delay 20 ${explist_islands} anim_islands.gif



exit

