#!/bin/ksh

indir_root=/home/bridge/ggdjl/umdata

#for exproot in tfgw tfgW tfGw tfGW tFgw ; do
#for exproot in tFke ; do
#  my_loop={a..z}

#for exproot in tfKE ; do
#    my_loop={a..h}

for exproot in tfke ; do
    my_loop={f..z}

#  if [ "$exproot" = "tFgw" ] ; then
  if [ "$exproot" = "tFke" ] ; then
    my_loop={a..e}
  fi


  for id in ${my_loop} ; do

    exp=${exproot}${id}
    indir=${indir_root}/${exp}/pg

    echo ${exp}

      if find ${indir}/* -maxdepth 0 -type f 2>/dev/null | read ; then 

        echo "running"
        /home/bridge/ggdjl/ggdjl/um/scripts/make_times_scr_new ${exp}

      fi

  done
done

exit
