#!/bin/ksh

#indir_root=/home/bridge/ggdjl/um_climates
indir_root=/home/ggdjl/ummodel/data

explist=''

#exptype1=tfks
exptype1=tfke
#exptype1=tfja
#exptype1=tfgw

exp1a=${exptype1}
exp1b=`sed 's/./\U&/4' <<< "${exp1a}"`
exp1c=`sed 's/./\U&/3' <<< "${exp1a}"`
exp1d=`sed 's/./\U&/3' <<< "${exp1b}"`
exp1e=`sed 's/./\U&/2' <<< "${exp1a}"`

exp2a=${exptype2}
exp2b=`sed 's/./\U&/4' <<< "${exp2a}"`
exp2c=`sed 's/./\U&/3' <<< "${exp2a}"`
exp2d=`sed 's/./\U&/3' <<< "${exp2b}"`
exp2e=`sed 's/./\U&/2' <<< "${exp2a}"`

expids1="${exp1a} ${exp1b} ${exp1c} ${exp1d} ${exp1e}"
expids2="${exp2a} ${exp2b} ${exp2c} ${exp2d} ${exp2e}"

echo ${expids1}
echo ${expids2}

#
for expid in ${expids1} ; do

   if [ "$expid" = ${exp1a} ] ; then
      expid_old=${exp2a}
      my_loop={a..z}
   elif [ "$expid" = ${exp1b} ] ; then
      expid_old=${exp2b}
      my_loop={a..z}
   elif [ "$expid" = ${exp1c} ] ; then
      expid_old=${exp2c}
      my_loop={a..z}
   elif [ "$expid" = ${exp1d} ] ; then
      expid_old=${exp2d}
      my_loop={a..z}
   elif [ "$expid" = ${exp1e} ] ; then
      expid_old=${exp2e}
      my_loop={a..e}
   fi

   for id in ${my_loop} ; do

     exp=${expid}${id}
     exr=${expid_old}${id}

     explist_uv_00=${explist_uv_00}' plots/uv_'${exp}_00'.pdf'
     explist_uv_11=${explist_uv_11}' plots/uv_'${exp}_11'.pdf'
     explist_uv_15=${explist_uv_15}' plots/uv_'${exp}_15'.pdf'
     explist_stream=${explist_stream}' plots/streamfn_'${exp}'.pdf'
     explist_mixed=${explist_mixed}' plots/mixed_'${exp}'.pdf'
     explist_merid=${explist_merid}' plots/merid_'${exp}'.pdf'
     explist_wind=${explist_wind}' plots/wind_'${exp}'.pdf'
     explist_salin=${explist_salin}' plots/salin_'${exp}'.pdf'
     explist_temp=${explist_temp}' plots/temp_'${exp}'.pdf'
     explist_precip=${explist_precip}' plots/precip_'${exp}'.pdf'
     explist_sat=${explist_sat}' plots/sat_'${exp}'.pdf'
     explist_topo=${explist_topo}' plots/topo_'${exp}'.pdf'
     explist_islands=${explist_islands}' ../islands/'${exr}'/newislands_'${exr}'-crop.pdf'

   done
done

#convert -loop 0 -delay 20 ${explist_uv_00} anim_uv_00.gif
#convert -loop 0 -delay 20 ${explist_uv_11} anim_uv_11.gif
#convert -loop 0 -delay 20 ${explist_uv_15} anim_uv_15.gif
#convert -loop 0 -delay 20 ${explist_stream} anim_stream.gif
#convert -loop 0 -delay 20 ${explist_mixed} anim_mixed.gif
#convert -loop 0 -delay 20 ${explist_merid} anim_merid.gif
#convert -loop 0 -delay 20 ${explist_wind} anim_wind.gif
#convert -loop 0 -delay 20 ${explist_salin} anim_salin.gif
#convert -loop 0 -delay 20 ${explist_temp} anim_temp.gif
#convert -loop 0 -delay 20 ${explist_topo} anim_topo.gif
#convert -loop 0 -delay 20 ${explist_islands} anim_islands.gif
#convert -loop 0 -delay 20 ${explist_precip} anim_precip.gif
convert -loop 0 -delay 20 ${explist_sat} anim_sat.gif

exit

