#!/bin/ksh

indir_root=/home/bridge/ggdjl/um_climates

#for exproot in tfgw tfgW tfGw tfGW tFgw ; do
for exproot in tfja tfjA tfJa tfJA tFja ; do

   if [ "$exproot" = "tfgw" ] ; then
      exproot_old="teye"      
      my_loop={a..z}
   elif [ "$exproot" = "tfgW" ] ; then
      exproot_old="teyE"
      my_loop={a..z}
   elif [ "$exproot" = "tfGw" ] ; then
      exproot_old="teYe"
      my_loop={a..z}
   elif [ "$exproot" = "tfGW" ] ; then
      exproot_old="teYE"
      my_loop={a..z}
   elif [ "$exproot" = "tFgw" ] ; then
      exproot_old="tEye"
      my_loop={a..e}
   fi

   if [ "$exproot" = "tfja" ] ; then
      exproot_old="tfgw"      
      my_loop={a..z}
   elif [ "$exproot" = "tfjA" ] ; then
      exproot_old="tfgW"
      my_loop={a..z}
   elif [ "$exproot" = "tfJa" ] ; then
      exproot_old="tfGw"
      my_loop={a..z}
   elif [ "$exproot" = "tfJA" ] ; then
      exproot_old="tfGW"
      my_loop={a..z}
   elif [ "$exproot" = "tFja" ] ; then
      exproot_old="tFgw"
      my_loop={a..e}
   fi


   for id in ${my_loop} ; do

     exp=${exproot}${id}
     exr=${exproot_old}${id}

     indir=${indir_root}/${exp}

     echo ${exp}

       if find ${indir}/${exp}a.pdclann.nc -maxdepth 0 -type f 2>/dev/null | read ; then 
         echo 'file exists so plotting'
         ./plot_clim_scotese ${exp} ${exr} 1
       else
         ./plot_clim_scotese ${exp} ${exr} 0
       fi

   done
done

exit

