#!/bin/ksh

indir_root=/home/bridge/ggdjl/um_climates

for exproot in tfgw tfgW tfGw tfGW tFgw ; do
   if [ "$exproot" = "tfgw" ] ; then
      exproot_old="teye"
      my_loop={a..z}
   elif [ "$exproot" = "tfgW" ] ; then
      exproot_old="teyE"
      my_loop={a..z}
   elif [ "$exproot" = "tfGw" ] ; then
      exproot_old="teYe"
      my_loop={a..z}
   elif [ "$exproot" = "tfGW" ] ; then
      exproot_old="teYE"
      my_loop={a..z}
   elif [ "$exproot" = "tFgw" ] ; then
      exproot_old="tEye"
      my_loop={a..e}
   fi

   for id in ${my_loop} ; do

     exp=${exproot}${id}

     indir=${indir_root}/${exp}

     echo ${exp}

     mkdir -p ~swsvalde/ummodel/data/${exp}/climate
     \cp ${indir}/${exp}o.pgclann.nc ~swsvalde/ummodel/data/${exp}/climate/
     ~swsvalde/ummodel/scripts/make_merid_ocean ${exp}   

   done
done

exit
