#!/bin/bash

indir_root=/home/bridge/ggdjl/umdata

#for exproot in tfgw tfgW tfGw tfGW tFgw ; do
#  for id in {a..z} ; do

#for exproot in tFke ; do
#  for id in {a..e} ; do

#for exproot in tfke ; do
#  for id in {a..e} ; do

#for exproot in tfke ; do
#    for id in {f..z} ; do

for exproot in tfks tfkS tfKs tfKS tFks ; do
for id in {a..z} ; do

    exp=${exproot}${id}
    indir=${indir_root}/${exp}/pg

    echo ${exp}

      if find ${indir}/*.nc -maxdepth 0 -type f 2>/dev/null | read ; then 
#        echo 'some netcdf files exist'
        numfiles=`find ~/umdata/${exp}/pg/*.nc -maxdepth 0 -type f 2>/dev/null | wc | awk '{print $1}'`
        echo ${numfiles}
#        if [ ${numfiles} == 199 ] ; then
#        if [[ ${numfiles} == 1050 ]] || [[ ${numfiles} == 1049 ]] ; then
#        if [[ ${numfiles} == 3000 ]] ; then
#        if [[ ${numfiles} -gt 205 ]] ; then
        if [[ ${numfiles} -gt 2000 ]] ; then

        echo "running as correct number of pg files"
#        /home/bridge/ggdjl/ggdjl/um/scripts/make_climate -y '0000020[3-4]?' ${exp}
#        /home/bridge/ggdjl/ggdjl/um/scripts/make_climate -y '0000028[7-9]?' ${exp}
#        /home/bridge/ggdjl/ggdjl/um/scripts/make_climate -y '0000029[7-9]?' ${exp}
#        /home/bridge/ggdjl/ggdjl/um/scripts/make_climate -y '00000019[5-9]' ${exp}
        /home/bridge/ggdjl/ggdjl/um/scripts/make_climate -y '00000199[0-9]' ${exp}
        fi
      fi

  done
done

exit
