#!/bin/bash

plot_tempdiff=0
plot_streamabs=0
plot_uv=1

###  get args
if [ "$#" -ne 3 ]; then
    echo "Illegal number of options: must be 3"
    exit
fi

###  setup
exp=${1}
exr=${2}
doplot=${3}

if [ ${plot_tempdiff} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_dif.ncl"
\cp ncl.SKEL.clim_dif.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_streamabs} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_abs.ncl"
\cp ncl.SKEL.clim_abs.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi


if [ ${plot_uv} -eq 1 ] ; then
for lev in 0 11 15 ; do
jobfile="ncl.${exp}.clim_uv.ncl"
\cp ncl.SKEL.clim_uv.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
sed -i "s/LEV/${lev}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
done
fi


exit
