#!/bin/bash


plot_tempdiff=0
plot_streamabs=0
plot_uv=0
plot_mixed=0
plot_merid=0
plot_wind=0
plot_temp=0
plot_sat=1
plot_salin=0
plot_topo=0
plot_albdiff=0
plot_smdiff=0
plot_precip=0
plot_globe=0



###  get args
if [ "$#" -ne 4 ]; then
    echo "Illegal number of options: must be 4"
    exit
fi

###  setup
exp=${1}
exr=${2}
age=${3}
doplot=${4}

if [ ${plot_topo} -eq 1 ] ; then
jobfile="ncl.${exp}.topo.ncl"
\cp ncl.SKEL.clim_topo.ncl ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi


if [ ${plot_tempdiff} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_dif.ncl"
\cp ncl.SKEL.clim_dif.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_albdiff} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_alb_dif.ncl"
\cp ncl.SKEL.clim_alb_dif.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_smdiff} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_sm_dif.ncl"
\cp ncl.SKEL.clim_sm_dif.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_streamabs} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_abs.ncl"
\cp ncl.SKEL.clim_abs.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/TYP/pf/g" ${jobfile}
sed -i "s/CODE/o/g" ${jobfile}
sed -i "s/FLIP/0/g" ${jobfile}
sed -i "s/MASK/1/g" ${jobfile}
sed -i "s/COL/BlueDarkRed18/g" ${jobfile}
sed -i "s/MAX/1.5e14/g" ${jobfile}
sed -i "s/MIN/-1.5e14/g" ${jobfile}
sed -i "s/DEL/1e13/g" ${jobfile}
sed -i "s/MX2/1.5e15/g" ${jobfile}
sed -i "s/MN2/-1.5e15/g" ${jobfile}
sed -i "s/DL2/2e13/g" ${jobfile}
sed -i "s/VAR/streamFn_mm_uo/g" ${jobfile}
sed -i "s/VSHORT/streamfn/g" ${jobfile}
sed -i "s/VLONG/Streamfunction/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi


if [ ${plot_mixed} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_abs.ncl"
\cp ncl.SKEL.clim_abs.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/TYP/pf/g" ${jobfile}
sed -i "s/CODE/o/g" ${jobfile}
sed -i "s/FLIP/0/g" ${jobfile}
sed -i "s/MASK/1/g" ${jobfile}
sed -i "s/COL/WhBlGrYeRe/g" ${jobfile}
sed -i "s/MAX/300/g" ${jobfile}
sed -i "s/MIN/100/g" ${jobfile}
sed -i "s/DEL/20/g" ${jobfile}
sed -i "s/MX2/1000/g" ${jobfile}
sed -i "s/MN2/100/g" ${jobfile}
sed -i "s/DL2/100/g" ${jobfile}
sed -i "s/VAR/mixLyrDpth_mm_uo/g" ${jobfile}
sed -i "s/VSHORT/mixed/g" ${jobfile}
sed -i "s/VLONG/Mixed Layer Depth/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi


if [ ${plot_salin} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_abs.ncl"
\cp ncl.SKEL.clim_abs.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/TYP/pg/g" ${jobfile}
sed -i "s/CODE/o/g" ${jobfile}
sed -i "s/FLIP/0/g" ${jobfile}
sed -i "s/MASK/1/g" ${jobfile}
sed -i "s/COL/BlAqGrYeOrReVi200/g" ${jobfile}
sed -i "s/MAX/0.005/g" ${jobfile}
sed -i "s/MIN/-0.005/g" ${jobfile}
sed -i "s/DEL/0.0005/g" ${jobfile}
sed -i "s/MX2/0.1/g" ${jobfile}
sed -i "s/MN2/-0.1/g" ${jobfile}
sed -i "s/DL2/0.002/g" ${jobfile}
sed -i "s/VAR/salinity_ym_dpth/g" ${jobfile}
sed -i "s/VSHORT/salin/g" ${jobfile}
sed -i "s/VLONG/Salinity/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_temp} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_abs.ncl"
\cp ncl.SKEL.clim_abs.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/TYP/pg/g" ${jobfile}
sed -i "s/CODE/o/g" ${jobfile}
sed -i "s/FLIP/0/g" ${jobfile}
sed -i "s/MASK/1/g" ${jobfile}
sed -i "s/COL/BlAqGrYeOrReVi200/g" ${jobfile}
sed -i "s/MAX/40/g" ${jobfile}
sed -i "s/MIN/-2/g" ${jobfile}
sed -i "s/DEL/2/g" ${jobfile}
sed -i "s/MX2/60/g" ${jobfile}
sed -i "s/MN2/-4/g" ${jobfile}
sed -i "s/DL2/4/g" ${jobfile}
sed -i "s/VAR/temp_ym_dpth/g" ${jobfile}
sed -i "s/VSHORT/temp/g" ${jobfile}
sed -i "s/VLONG/Ocean temperature/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_precip} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_abs.ncl"
\cp ncl.SKEL.clim_abs.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/TYP/pd/g" ${jobfile}
sed -i "s/CODE/a/g" ${jobfile}
sed -i "s/FLIP/0/g" ${jobfile}
sed -i "s/MASK/0/g" ${jobfile}
sed -i "s/COL/CBR_drywet/g" ${jobfile}
sed -i "s/MAX/1e-4/g" ${jobfile}
sed -i "s/MIN/0/g" ${jobfile}
sed -i "s/DEL/5e-6/g" ${jobfile}
sed -i "s/MX2/3e-4/g" ${jobfile}
sed -i "s/MN2/0/g" ${jobfile}
sed -i "s/DL2/5e-5/g" ${jobfile}
sed -i "s/VAR/precip_mm_srf/g" ${jobfile}
sed -i "s/VSHORT/precip/g" ${jobfile}
sed -i "s/VLONG/Precipitation/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_sat} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_abs.ncl"
\cp ncl.SKEL.clim_abs.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/TYP/pd/g" ${jobfile}
sed -i "s/CODE/a/g" ${jobfile}
sed -i "s/FLIP/0/g" ${jobfile}
sed -i "s/MASK/0/g" ${jobfile}
sed -i "s/COL/BlAqGrYeOrReVi200/g" ${jobfile}
sed -i "s/MAX/300.0/g" ${jobfile}
sed -i "s/MIN/250.0/g" ${jobfile}
sed -i "s/DEL/5.0/g" ${jobfile}
sed -i "s/MX2/10.0/g" ${jobfile}
sed -i "s/MN2/-10.0/g" ${jobfile}
sed -i "s/DL2/1.0/g" ${jobfile}
sed -i "s/VAR/temp_mm_1_5m/g" ${jobfile}
sed -i "s/VSHORT/sat/g" ${jobfile}
sed -i "s/VLONG/Surface Air Temperature/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi


if [ ${plot_uv} -eq 1 ] ; then
for lev in 0 11 15 ; do
jobfile="ncl.${exp}.clim_uv.ncl"
\cp ncl.SKEL.clim_uv.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
sed -i "s/LEV/${lev}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
done
fi

if [ ${plot_wind} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_wind.ncl"
\cp ncl.SKEL.clim_wind.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi


if [ ${plot_merid} -eq 1 ] ; then
jobfile="ncl.${exp}.clim_merid.ncl"
\cp ncl.SKEL.clim_merid.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi

if [ ${plot_globe} -eq 1 ] ; then
jobfile="ncl.${exp}.globe.ncl"
\cp ncl.SKEL.clim_globe.ncl ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/AGE/${age}/g" ${jobfile}
sed -i "s/DOPLOT/${doplot}/g" ${jobfile}
ncl ${jobfile}
\rm ${jobfile}
fi


exit
