#!/bin/bash

plot_var=1
crop_plots=0

###  get args
if [ "$#" -ne 2 ]; then
    echo "Illegal number of options: must be 2"
    exit
fi

###  setup
exp=${1}
exr=${2}

if [ ${plot_var} -eq 1 ] ; then

jobfile="ncl.${exp}.clim.ncl"
\cp ncl.SKEL.clim.ncl ${jobfile}
sed -i "s/EXP/${exp}/g" ${jobfile}
sed -i "s/EXR/${exr}/g" ${jobfile}
ncl ${jobfile}

if [ ${crop_plots} -eq 1 ] ; then
pdfcrop plots/temp_${exp}.pdf &
fi

fi

exit
